---
title: "Weekly Update 3"
author: "Lee Van Brussel and Zachary Levine"
date: '2020-11-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(lubridate)
library(anytime)
library(epigrowthfit)
df <- read.csv("COVID19_cases.csv")
df$Date <- anytime::anydate(df$Reported.Date)
ageClasses <- unique(df$Age.Group)
doublingtimes <- c()
egfs <- list()
for (ageGroup in ageClasses){
  currentDf <- df[df$Age.Group == ageGroup,]
  freq <- currentDf %>%
  group_by(Date) %>%
  summarize(n=n())
  freq$Date <- anytime::anydate(freq$Date)
  wave1egf <- egf(egf_init(date = freq$Date, cases = freq$n, peak = smooth_cases(date = freq$Date, cases = freq$n, log = FALSE, spar = 0.4)$peaks[2]))
  wave2egf <- egf(egf_init(date = freq$Date, cases = freq$n, peak = smooth_cases(date = freq$Date, cases = freq$n, log = FALSE, spar = 0.4)$peaks[length(smooth_cases(date = freq$Date, cases = freq$n, log = FALSE, spar = 0.4)$peaks)]))
  doublingtimes <- c(doublingtimes, c("first" = compute_doubling_time(wave1egf), "second" = compute_doubling_time(wave2egf)))
    egfs <- c(egfs, list("first" = wave1egf, "second" = wave2egf))
}
doublingtimes <- data.frame(doublingtimes)
labs <- c()
for (i in 1:length(ageClasses)){
  ##Even entries correspond to the second wave.
  if (i %% 2  == 0){
    labs <- c(labs, paste(ageClasses[i], "second", sep = "-"))
  }
  else{
    labs <- c(labs, paste(ageClasses[i], "first", sep = "-"))
  }
}
doublingtimes$type <- labs
```
